def main():
    dna = 'TCTTAAGAGGGATGAAGAAAACTCCCGCGTCAACCATTATAGAATGCCGTTACGAGCGCGAACCATAGGCTCAATGAGTATCATCGAGAGGACCCTCGCTTCGTTCCCGATGCAATCAAGAAGGAAAGATATTTGCAGTTAGATGCCATCCCGACGGGTAAATGCCACTGGGGACGTACGCGAACATCAGAACACATCTTGGCTTCCAATACGTTGTCAGACTAGTTCGAGAGCCGTTTCCTTAGGTCTAGGCTGCGTTTTAAATTACATCTATACGACTCCAGCCTAGGCACTCGTGGCTCACATAACAGGACCGGGCGCCGAGGCGACTAAGGCGTTTGAAGCTATGTTGGACTCGCGAGAGGAAAGATCGACCAAAAGTTGTTGTGGAGATGAAAGCGTAGAGACTAAGTTAAAGCAACTCAATGGGCGCAAATATGAACAAATGCGCATCTTATGTGCCTTCTAACGTAGATCATTCGCCGTAGACAATATAGAGATGCACTCCCCGAAGAAAAGAGGAGACAGAATGCAACACCATTTTGGTTATACCAGATGCTAGTGACACGACTCCGTGGGTTTGGCGACCGGTGCGATCCATTTTGCGGTTACATGCCCGTGTTTCAATTTTGTGTAGTCACCCACATTGAGTAGTCGTTCCAGTGGTTTATGTGGGTACTAATTTGTCATTACGCGCCCTTAACTTCTCCCTAGTAGGTTAGCGGTGTAGCACTGACACGGGTTATATTATCACATGCGTAAGTCGGCCTGCGGTTGCTGGGGTGCACTATCGTACCCAATGCAGGGCACCGTCGGGAGGCAACACCTTCCCTAGAAGATGAGCGATCGCCGCTGACCGTTATTTCCTTATCGAAGTTAACAGACTTTAGTCTTTTGCGTTGTTATCTCTCGATCCTGGTTAGATTAGGGCGTAGTGACGCTTATACTTCATAGCTGATCGTGCTGGCGCGGCCCCTGACAGGTAGTCA'
    result_integer = sample(dna)
    print(result_integer['A'],result_integer['C'],result_integer['G'],result_integer['T'])
def sample(dna):
    dict= {'A':0,'C':0,'G':0,'T':0}
    for a_base in dna:
        if a_base in dict:
            dict[a_base] +=1
    return dict
if __name__ == "__main__":
      main()
