# Rosalind: Complementing a Strand of DNA
# Input: DNA string -> Output: reverse complement (A<->T, G<->C, then reversed)

def main():
    dna = 'TTAATGGAGTGTCGCCCCCACTTTCAAAGGTTAACCCGCTTCTGAGCTGTAGGCGTCGGTGCTCTCATGTGTCAGGCGACATTGTGGCTTAGGACTGAAAAGCAAACAGGCACCACCAGTTTTGAACGAAGGGCCTATTACTTCTCTGGCTTTACCGCACGCGTGCGGTGGATAGTGCTTATGAGTGCCACGACGGTCAACCGATCTCCACCCACACGCGGGTTAACAGTAACATTTAGTCAAAGTGAGTAGCGCTGCCCACGAGGAGTAAACATCAAAGGATACACTTGTGCGACCCCTGCCAGTTGACGGCCTTAATAATCAAAATAGTTCTAGGTCCTCTGCGGCCCATCCTGCTTTCACCCATTTGTCCCGCGCAAGTATGCGTGAACTACCCACATGGGGTCAAGACCGTGCGTCCTGACTTATAGGTAGCGCCAAGGGGTCGTAAAGCCCTCCGCCAATCAACTAGAGGGACGACGCAGTCAATGACCGGCGGCATGGCGGCAACCAATGTCTTCTTACACGTCACCTCAGGGGGTCTATTTCAAGAACCTGAGGTTCTGGTTGTGGGAACCTGCTGATGCGTGGATTTCTACTTGACACTTGTTCATTACGCTGGAGCAGTCCGGGGCGCGGCCTCAACAGGGCTCCCACCTGGTCAACAATCAAAGTTCTAAAGATGAATATTCTTGGTGAGCTTAGCGAGCTCGATTAATGACTCAGACGCTGTCAATTCTCATAGCGGCGGCGGCTGCAGCCGTATCCATGCTGTTAGGAGACGTCTATATGTATACGAGGTGGCCCGAATGCTTAATTCAACGTGACCTGTTA'
    print(sample(dna))
def sample(dna):
    dict = {'A':'T','T':'A','C':'G','G':'C'}
    new_dna = ''
    for evry_base in dna:
        if evry_base in dict:
            new_dna += dict[evry_base]
            reverse_dna = new_dna[::-1]
    return reverse_dna
if __name__ == "__main__":
      main()